### PR TITLE
Fixing docker-compose setup to include git repo

### PR DESCRIPTION
**Pull request by fruch**
I found it a bit trickey to configure the git setup
So I've documented into the docker-compose setup.

Now out of the box, you can have git configured with a local file based repo

```bash
root@0f0a7a8e59a0:/go/src/github.com/vsco/dcdr# cat /etc/dcdr/decider.json
{
  "dcdr": {
    "info": {
      "current_sha": "65e3b58fe63c9d5ba0d521fd0e5a0afbdea8385a",
      "last_modfied_date": 1520836148
    },
    "features": {
      "default": {
        "test1": true
      }
    }
  }
```

### CODE REVIEW

**Comment by fruch** [comment]
hmm travis... (I hope the compose isn't used there.. we'll find out soon enough :))

**Comment by fruch** [comment]
there is some instability in the watch test (in windows it's failing constently)

**Comment by fruch** [comment]
@negator care to review this one ?

**Comment by promiseofcake** [comment]
Hi there @fruch, thanks so much for the contribution, I will be getting a review out for this today.

**Comment by fruch** [comment]
FYI, I'm working on clients for the dcdr Server in both python and node.js (while trying to pitch for using dcdr, or at least the same concepts in the projects I'm working at)

I'll upload them if/when I'll sort the legal stuff.

**Comment by promiseofcake** [comment]
Added a PR to address the `docker-compose` example: https://github.com/vsco/dcdr/pull/67

**Comment by fruch** [comment]
seperated each issue into it's own PR,

about this one, I think having a way to show how to setup git is really helpful.
I was trying to see how to use the ETag for cacheing, and found out that it would be available on when git is enabled (would be a nice feature if we could checksum the feature json, and use that for the `current_sha`)

**Comment by fruch** [comment]
so you think we can put the example I did for setup of git in a separate repo ?

**Comment by smullins7** [comment]
I'm new and seeing this PR for the first time - is this still applicable/desired?

**Comment by promiseofcake** [comment]
In my opinion it isn't necessary to have the git functionality built into this "out of the box see it works" demo.

With regards to:

> I think having a way to show how to setup git is really helpful.

I do think that is important, but I don't think it should fall into the docker-compose paradigm.

**Pull request closed without merging**
